name: crypto_tracker
description: Крипто-трекер (Flutter + CoinPaprika + Binance + fl_chart + темы)
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.2              # обязательно 0.20.2, чтобы совпадало с flutter_localizations
  fl_chart: ^0.66.2
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2 # <— нужна для сохранения темы

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
