name: crypto_tracker
description: Крипто-трекер (Flutter + CoinPaprika + Binance WS/REST + fl_chart + Portfolio)
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.2
  fl_chart: ^0.69.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1   # <-- добавьте ЭТО

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
